menu:
    about: /about/
    code: https://github.com/raffazizzi
    twitter: https://twitter.com/raffazizzi
    publications: https://umd.academia.edu/RaffaeleViglianti

favicon: /favicon.ico
logo: /logo.png

# Comment
disqus: itisnotsound

# Analytics
google-analytics:
ga: UA-89416245-1

# theme version
version: 1.0.2.z
# theme branch
branch: next
# theme font cdn url
font: //fonts.googleapis.com/css?family=Questrial
# theme style cdn url
css: /css/main.css
